name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  camera: ^0.10.0+1
  cross_file: ^0.3.3+1
  flutter:
    sdk: flutter
  tensorflow_models:
    path: ../
  vector_math: ^2.1.2
  zflutter:
    git: 
      url: https://github.com/jamesblasco/zflutter
      path: zflutter
      ref: bde6f320d6d278a82f40420df68a1ab4c466ba4c

dev_dependencies:
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
